### ISSUE TITLE
Question: Not really about ledger but.

### ISSUE THREAD

**Issue by justinjk007** [awalker4/ledgerTalk2016#1]
How did you make a pdf out of the Reveal slides. ?

**Comment by awalker4** [comment]
It's been a while, but I believe I was able to print from the browser as documented [here](https://github.com/hakimel/reveal.js#pdf-export). For best results you'll need to run your presentation as a server (instructions [here](https://github.com/hakimel/reveal.js#full-setup)). Let me know if it works!

**Comment by justinjk007** [comment]
Yes, reading through the documentation I found out [decktape](https://github.com/astefanutti/decktape). This worked out for me.
